---
title: "Package plotly"
author: "Marylene Henry"
date: "mars 2019"
output: 
  html_document :
    toc: true
    toc_float: true
    toc_depth: 3
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Graphiques interactifs {.tabset}

Dans une visualisation statique, le nombre de dimensions de repr&eacute;sentation des donn&eacute;es est limit&eacute;. Repr&eacute;senter une information multidimensionnelle proprement &agrave; l’aide d’une repr&eacute;sentation statique est difficile. La visualisation statique reste id&eacute;ale lorsque l’information &agrave; repr&eacute;senter n’est pas tr&egrave;s complexe ou riche. Elle est requise lorsque le m&eacute;dium de publication est un support papier.

Le package `plotly` vous permettra de r&eacute;aliser des graphiques int&eacute;ractifs. 

### Graphiques statiques / dynamiques / int&eacute;ractif : quels usages ?

**Quelle est la diff&eacute;rence entre des graphiques dynamiques et des graphiques int&eacute;ractifs ?**

G&eacute;n&eacute;ralement, le terme "interactivit&eacute;" est plut&ocirc;t utilis&eacute; pour la communication et la restitution des r&eacute;sultat tandis que "les graphiques dynamiques" sont plut&ocirc;t utiles pour la phase exploratoire.  
Cependant les deux termes sont souvent associ&eacute;s ou utilis&eacute;s l'un pour l'autre. 

### Int&eacute;r&ecirc;t pour la datavisualisation

Les visualisations dynamiques et interactives participent de l’exp&eacute;rience utilisateur. Le lecteur est alors autonome dans la compr&eacute;hension qu’il se fera des donn&eacute;es. Les donn&eacute;es sont alors accessibles &agrave; des audiences diff&eacute;rentes gr&agrave;ce aux fonctionnalit&eacute;s offertes par l’interactivit&eacute; – que ce soit pour les utilisateurs non sp&eacute;cialistes de la donn&eacute;e qui pourront se balader dans le jeu de donn&eacute;es ou pour les utilisateurs plus avertis qui ont une question tr&egrave;s sp&eacute;cifique et qui rechercheront une r&eacute;ponse pr&eacute;cise lors de l’exploration des donn&eacute;es.



## Introduction &agrave; l'utilisation du package `plotly` 

### cr&eacute;er son graphique interactif {.tabset}

#### convertir un graphique `ggplot2`

#### Testons

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

### Un outil cl&eacute; customisable : `Hover info`

Par d&eacute;faut, l'option `hoverinfo` va permettre de g&eacute;rer l'information affich&eacute;e lorsque l'on balaye un graphique r&eacute;alis&eacute; avec plotly.

- `all` : affiche tous les &eacute;l&eacute;ments
- `x` : affiche les &eacute;l&eacute;ments relatifs &agrave; la variable `x`  
- `y` : affiche les &eacute;l&eacute;ments relatifs &agrave; la variable `y`  
- `x+y`  
- `x+y+z`  

On peut &eacute;galement avoir envie de personnaliser l'affichage avec du texte. Il faut dans ce cas utiliser le param&egrave;tre suppl&eacute;mentaires : `text` 
