---
title: 'Dataviz et packages R '
author: "Marylene Henry"
date: "Avril 2019"
output:
  ioslides_presentation:
    logo: "images/URFIST.jpg"
    css: style.css
autosize: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(htmltools)
library(dplyr)
library(tibble)
library(ggplot2)
library(plotly)
library(lattice)
options(tibble.print_max = 15)
options(tibble.print_min = 6)
```

```{css firstpagebg, echo=FALSE}
.title-slide {
  background-size: cover;
  background-position: center;
  background-blend-mode: lighten;
  text-align: left;
  
}
```



## **Visualiser ses donn&eacute;es avec R** {data-background=C:/Users/maryl/Urfist/dataviz_avancee/slides_cours/images/feuille_outils2.jpg data-background-size=cover .bigger .flexbox .vcenter}

<div class="black" >
<font size="6.6">

- Les 4 syst&egrave;mes graphiques en `R`

- Quelle strat&eacute;gie adopter pour repr&eacute;senter mes donn&eacute;es

</font>
</div>

## Dplyr - un package du tidyverse {data-background=images/tidyverse.png data-background-size=cover}

<div class="columns-2">
<div class="green3">
<br></br>
<br></br>
<font size="6">
- Logiques de sythaxe des diff&eacute;rents packages  
  
- Options avanc&eacute;es de personnalisation    
    + bdjd
    + jhdiu
</font>    
</div>
  
<div class="green3">

<br></br>
<br></br>
<font size="6">

- Langage `R` Base ?

- Le tidyverse ?

</font>
</div>  
  
</div>


## Ce que nous n'aurons pas le temps d'aborder  

>- 

## Etre efficace dans son apprentissage


## Avoir les bons r&eacute;flexes

1. Une communaut&eacute; riche  
    +   
    + `ROpenSci`  
    + .... 
    
2. Regarder ce que font d'autres acteurs de la visualisation de la donn&eacute;e

## Le package `ggplot2` ?

### Pourquoi il est int&eacute;ressant de conna&icirc;tre la synthaxe de ce package ?
<br></br>  

> - bas&eacute; sur *"the grammar of graphics"*  
> - &eacute;cosyst&egrave;me riche : beaucoup de packages reprennent la logique de `ggplot2`  
> - un package du `tidyverse`

## Exemples de dataviz 

[Exemples de datavisualisation](https://uxplanet.org/functional-visualization-vs-artistic-dashboarding-8764cc117aa9)

[Exemples originaux de dataviz et musique](https://towardsdatascience.com/data-visualization-in-music-11fcd702c893)




